### ISSUE TITLE
nested json

### ISSUE THREAD

**Issue by ralphlayog** [readmeio/oas#10]
Hi! how do I create a nested json?
I cant find a way on how to create it using this oas.

Thanks!

**Comment by gkoberger** [comment]
Hey! This just uses normal OpenAPI stuff, so anything you can do there, you can do here!

So, let's say you want this as the response:

```
{
    "CountryCombo": {
        "options": {
            "option": [{
                "id": "GB",
                "value": "GB Great Britain"
            }, {
                "id": "US",
                "value": "US United States"
            }, {
                "id": "AD",
                "value": "AD Andorra, Principality of"
            }]
        }
    }
}
```

Your YAML would look something like:

```yaml
CountryCombo:
    type: object
    properties:
        options:
            type: object
            properties:
                option:
                    type: array
                    items:
                        type: object
                        properties:
                          id:
                            type: string
                          value:
                            type: string
```
