### ISSUE TITLE
Numeric bounds added to non-numeric fields

### ISSUE THREAD

**Issue by Suficio** [readmeio/oas#794]
Adding a numeric `format` field to non-numeric `type` generates numeric bounds in JSON Schema

Example OpenAPI definition:

```yaml
- name: steamid
   in: query
   description: Steam ID of user making purchase.
   schema:
     type: string
     format: uint64
```

Resulting invalid schema:

```js
{
    type: 'string',
    format: 'uint64',
    minimum: 0,
    maximum: 18446744073709552000,
}
```
